name: android_video_converter
description: A video file converter app for Android
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # ffmpeg_kit_flutter: ^6.0.3  # Repository issue
  video_compress: ^3.1.3  # Alternative video processing
  file_picker: ^8.1.2
  path_provider: ^2.0.15
  permission_handler: ^11.3.1
  provider: ^6.0.5
  video_player: ^2.7.0
  flutter_riverpod: ^2.3.6
  go_router: ^16.0.0
  shared_preferences: ^2.2.2
  flutter_colorpicker: ^1.1.0
  video_thumbnail: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true